/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view;

import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author 84968
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Home() {
        initComponents();

        this.setSize(1366,768);
        hocluat.setIcon(new ImageIcon("Images/HocLuat.png"));
        thitracnghiem.setIcon(new ImageIcon("Images/THITRNG.png"));
        gioithieu.setIcon(new ImageIcon("Images/GioiThieu.png"));
        thoat.setIcon(new ImageIcon("Images/Thoat.png"));
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        hocluat = new javax.swing.JLabel();
        thitracnghiem = new javax.swing.JLabel();
        gioithieu = new javax.swing.JLabel();
        thoat = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 3));
        getContentPane().add(jLabel6);

        jPanel1.setLayout(new java.awt.GridLayout(6, 1));
        jPanel1.add(jLabel5);

        hocluat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hocluat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hocluatMouseClicked(evt);
            }
        });
        jPanel1.add(hocluat);

        thitracnghiem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thitracnghiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thitracnghiemMouseClicked(evt);
            }
        });
        jPanel1.add(thitracnghiem);

        gioithieu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gioithieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gioithieuMouseClicked(evt);
            }
        });
        jPanel1.add(gioithieu);

        thoat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thoatMouseClicked(evt);
            }
        });
        jPanel1.add(thoat);

        getContentPane().add(jPanel1);
        getContentPane().add(jLabel7);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hocluatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hocluatMouseClicked
       LearnLaw le = new LearnLaw();
            le.setVisible(true);
              this.dispose();
    }//GEN-LAST:event_hocluatMouseClicked

    private void thitracnghiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thitracnghiemMouseClicked
        ThiTracNghiem thtrng = new ThiTracNghiem();
            thtrng.setVisible(true);
              this.dispose();
    }//GEN-LAST:event_thitracnghiemMouseClicked

    private void gioithieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gioithieuMouseClicked
        Introduce in = new Introduce();
            in.setVisible(true);
              this.dispose();
    }//GEN-LAST:event_gioithieuMouseClicked

    private void thoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thoatMouseClicked
        System.exit(0);
    }//GEN-LAST:event_thoatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gioithieu;
    private javax.swing.JLabel hocluat;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel thitracnghiem;
    private javax.swing.JLabel thoat;
    // End of variables declaration//GEN-END:variables
}
