/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view;

import javax.swing.ImageIcon;

/**
 *
 * @author 84968
 */
public class LearnLaw extends javax.swing.JFrame {

    /**
     * Creates new form LearnLaw
     */
    public LearnLaw() {
        initComponents();
        this.setSize(1366,768);
        back_hocluat.setIcon(new ImageIcon("Images/Back.png"));
        luatduongbo.setIcon(new ImageIcon("Images/LuatDuongBo.png"));
        luatduongsat.setIcon(new ImageIcon("Images/LuatDuongSat.png"));
        luatduongthuy.setIcon(new ImageIcon("Images/LuatDuongThuy.png"));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        back_hocluat = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        luatduongbo = new javax.swing.JLabel();
        luatduongsat = new javax.swing.JLabel();
        luatduongthuy = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(5, 5));

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        jPanel2.setLayout(new java.awt.GridLayout(1, 4));

        back_hocluat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back_hocluat.setIcon(new javax.swing.ImageIcon("D:\\Github\\Project2_ATGT\\Project2\\Images\\Back.png")); // NOI18N
        back_hocluat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_hocluatMouseClicked(evt);
            }
        });
        jPanel2.add(back_hocluat);
        jPanel2.add(jLabel4);
        jPanel2.add(jLabel5);
        jPanel2.add(jLabel3);

        jPanel1.add(jPanel2);
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1);

        luatduongbo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        luatduongbo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                luatduongboMouseClicked(evt);
            }
        });
        getContentPane().add(luatduongbo);

        luatduongsat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        luatduongsat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                luatduongsatMouseClicked(evt);
            }
        });
        getContentPane().add(luatduongsat);

        luatduongthuy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        luatduongthuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                luatduongthuyMouseClicked(evt);
            }
        });
        getContentPane().add(luatduongthuy);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void luatduongsatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_luatduongsatMouseClicked
        LuatDuongSat la = new LuatDuongSat();
            la.setVisible(true);
              this.dispose();
    }//GEN-LAST:event_luatduongsatMouseClicked

    private void luatduongthuyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_luatduongthuyMouseClicked
        LuatDuongThuy lu = new LuatDuongThuy();
            lu.setVisible(true);
              this.dispose();
    }//GEN-LAST:event_luatduongthuyMouseClicked

    private void luatduongboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_luatduongboMouseClicked
       LuatDuongBo lu = new LuatDuongBo();
             lu.setVisible(true);
              this.dispose();
    }//GEN-LAST:event_luatduongboMouseClicked

    private void back_hocluatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_hocluatMouseClicked
         Home lo = new Home();
            lo.setVisible(true);
              this.dispose();
    }//GEN-LAST:event_back_hocluatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LearnLaw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LearnLaw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LearnLaw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LearnLaw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LearnLaw().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back_hocluat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel luatduongbo;
    private javax.swing.JLabel luatduongsat;
    private javax.swing.JLabel luatduongthuy;
    // End of variables declaration//GEN-END:variables
}
