/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;

/**
 *
 * @author Admin
 */
public class NewClass1 extends JFrame {

    public NewClass1() {

        setLayout(new GridLayout(3, 1));
        String vl = "This method is called from within the constructor to initialize the form.  WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.";
        int total = 3;
        JRadioButton[] radioArra = new JRadioButton[total];
        ButtonGroup group = new ButtonGroup();
        for (int i = 0; i < total; i++) {
            JRadioButton radio = new JRadioButton();
            radioArra[i] = radio;
            radio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unselected.png")));
            group.add(radio);
            radio.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    Enumeration<AbstractButton> elements = group.getElements();
                    while (elements.hasMoreElements()) {
                        JRadioButton selectedRadio = (JRadioButton) elements.nextElement();
                        selectedRadio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unselected.png")));
                    }
                    radio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/selected.png")));
                }
            });

            JTextArea jTextArea = new JTextArea(vl);
            jTextArea.setName(i + "");
            jTextArea.addFocusListener(new FocusAdapter() {
                @Override
                public void focusGained(FocusEvent e) {
                    JTextArea txt = (JTextArea) e.getComponent();
//                    super.focusGained(e); //To change body of generated methods, choose Tools | Templates.
                    Enumeration<AbstractButton> elements = group.getElements();
                    while (elements.hasMoreElements()) {
                        JRadioButton selectedRadio = (JRadioButton) elements.nextElement();
                        selectedRadio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unselected.png")));
                    }
                    radioArra[Integer.parseInt(txt.getName())].setIcon(new javax.swing.ImageIcon(getClass().getResource("/selected.png")));
                }

            });
            jTextArea.setLineWrap(true);
            jTextArea.setEditable(false);

            JPanel panel = new JPanel(new GridLayout(1, 2));
            panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            panel.add(radio);
            panel.add(jTextArea);
            
            
            getContentPane().add(panel);

        }

        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(400, 400);
        setVisible(true);
    }

    public static void main(String[] args) {
        new NewClass1();
    }
}
