/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view;

import com.dao.getTraffficforShow;
import com.model.Trafficsigns;
import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.Action;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.ScrollPaneConstants;

/**
 *
 * @author Admin
 */
public class ShowListTraffic extends javax.swing.JFrame {

    /**
     * Creates new form ShowListTraffic
     */
    class MouseEv extends MouseAdapter {
        String link;
        public MouseEv() {
            super();
        }

        public void mouseClicked(MouseEvent evt) {
            JDialog dialog = new JDialog();
            dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
            dialog.setTitle("Image Loading Demo");
            JLabel jLabel = new JLabel();
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(link).getImage().getScaledInstance(500, 500, Image.SCALE_DEFAULT));
            jLabel.setIcon(imageIcon);
            dialog.add(jLabel);
            
            dialog.pack();
            dialog.setLocationRelativeTo(null);
            dialog.setVisible(true);
        }

        public void setImageIcon(String linkk) {
            link=linkk;
        }

    }
    private ArrayList<Trafficsigns> listt = new ArrayList<>();
    int index = 0;
    private ArrayList<JLabel> arrayListlabel = new ArrayList<>();

    public ShowListTraffic() {
        initComponents();

        getTraffficforShow traffficforShow = new getTraffficforShow();
        listt = traffficforShow.gettraffic(7);

        for (int k = 0; k < listt.size(); k++) {
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(listt.get(k).getTrafficLink()).getImage().getScaledInstance(200, 200, Image.SCALE_DEFAULT));
            JLabel a = new JLabel();
            a.setIcon(imageIcon);
            arrayListlabel.add(k, a);
        }
        int row = 0;
        if (arrayListlabel.size() % 5 == 0) {
            row = arrayListlabel.size() / 5;
        } else {
            row = arrayListlabel.size() / 5 + arrayListlabel.size() % 5;
        }
        JPanel jPanel = new JPanel();

        jPanel.setLayout(new GridLayout(row, 5));

        for (JLabel jLabel : arrayListlabel) {
            jPanel.add(jLabel);
        }
        jScrollPane1.setViewportView(jPanel);
        jScrollPane1.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
        this.getContentPane().add(jScrollPane1, BorderLayout.CENTER);
        MouseEv mouseEv = null;
        
        for (int i = 0; i < arrayListlabel.size(); i++) {
            mouseEv = new MouseEv();
            mouseEv.setImageIcon(listt.get(i).getTrafficLink());
            arrayListlabel.get(i).addMouseListener(mouseEv);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowListTraffic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowListTraffic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowListTraffic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowListTraffic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowListTraffic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
