/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view;

import javax.swing.ImageIcon;

/**
 *
 * @author 84968
 */
public class ThiTracNghiem extends javax.swing.JFrame {

    /**
     * Creates new form LearnLaw
     */
    public ThiTracNghiem() {
        initComponents();
        this.setSize(1366, 768);
        back_thitracnghiem.setIcon(new ImageIcon("Images/Back.png"));
        thiduongbo.setIcon(new ImageIcon("Images/ThiDuongBo.png"));
        thixe2banh.setIcon(new ImageIcon("Images/Xe2Banh.png"));
        thixe4banh.setIcon(new ImageIcon("Images/Xe4Banh.png"));
        thiduongsat.setIcon(new ImageIcon("Images/ThiDuongSat.png"));
        thiduongthuy.setIcon(new ImageIcon("Images/ThiDuongThuy.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back_thitracnghiem = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        thiduongbo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        thixe2banh = new javax.swing.JLabel();
        thixe4banh = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        thiduongsat = new javax.swing.JLabel();
        thiduongthuy = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.blue);
        getContentPane().setLayout(new java.awt.GridLayout(8, 3));

        back_thitracnghiem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        back_thitracnghiem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        back_thitracnghiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_thitracnghiemMouseClicked(evt);
            }
        });
        getContentPane().add(back_thitracnghiem);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel2);

        thiduongbo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thiduongbo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(thiduongbo);

        jPanel1.setLayout(new java.awt.GridLayout(1, 4));
        jPanel1.add(jLabel8);

        thixe2banh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thixe2banh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        thixe2banh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thixe2banhMouseClicked(evt);
            }
        });
        jPanel1.add(thixe2banh);

        thixe4banh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thixe4banh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        thixe4banh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thixe4banhMouseClicked(evt);
            }
        });
        jPanel1.add(thixe4banh);
        jPanel1.add(jLabel9);

        getContentPane().add(jPanel1);

        thiduongsat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thiduongsat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        thiduongsat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thiduongsatMouseClicked(evt);
            }
        });
        getContentPane().add(thiduongsat);

        thiduongthuy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thiduongthuy.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        thiduongthuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thiduongthuyMouseClicked(evt);
            }
        });
        getContentPane().add(thiduongthuy);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel6);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel7);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_thitracnghiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_thitracnghiemMouseClicked
        Home lo = new Home();
        lo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back_thitracnghiemMouseClicked

    private void thixe2banhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thixe2banhMouseClicked
        System.setProperty("cateid", 1 + "");
        Test xe2 = new Test();
        xe2.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_thixe2banhMouseClicked

    private void thixe4banhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thixe4banhMouseClicked
        System.setProperty("cateid", 2 + "");
        Test xe2 = new Test();
        xe2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_thixe4banhMouseClicked

    private void thiduongsatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thiduongsatMouseClicked
        System.setProperty("cateid", 3 + "");
        Test xe2 = new Test();
        xe2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_thiduongsatMouseClicked

    private void thiduongthuyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thiduongthuyMouseClicked
        System.setProperty("cateid", 4 + "");
        Test xe2 = new Test();
        xe2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_thiduongthuyMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThiTracNghiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThiTracNghiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThiTracNghiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThiTracNghiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThiTracNghiem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back_thitracnghiem;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel thiduongbo;
    private javax.swing.JLabel thiduongsat;
    private javax.swing.JLabel thiduongthuy;
    private javax.swing.JLabel thixe2banh;
    private javax.swing.JLabel thixe4banh;
    // End of variables declaration//GEN-END:variables
}
