/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view;

import com.dao.getUserIDforlogin;
import com.model.Users;
import java.awt.Font;
import java.awt.GridLayout;
import java.util.Base64;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author 84968
 */
public class YourProfile extends javax.swing.JFrame {

    /**
     * Creates new form Introduce
     */
    private Users u;

    public YourProfile() {
        initComponents();
        this.setSize(1366, 768);
        this.setLocationRelativeTo(null);
        getUserIDforlogin userIDforlogin = new getUserIDforlogin();
        int iduss = Integer.parseInt(System.getProperty("userid"));
        u = userIDforlogin.get1usser(iduss);
        back_gioithieu.setIcon(new ImageIcon("Images/Back.png"));
        Username.setLayout(new GridLayout(1, 2));

        JLabel jLabelusernametitle = new JLabel("Tên tài khoản:");
        JLabel jLabelusername = new JLabel(u.getUsername());
        jLabelusernametitle.setFont(new Font("a", Font.PLAIN, 24));
        jLabelusername.setFont(new Font("a", Font.PLAIN, 24));

        Username.add(jLabelusernametitle);
        Username.add(jLabelusername);

        Password.setLayout(new GridLayout(1, 2));
        JLabel jLabelpasswordtitle = new JLabel("Mật khẩu:");
        jLabelpasswordtitle.setFont(new Font("a", Font.PLAIN, 24));

        Password.add(jLabelpasswordtitle);
        Password.add(buttonChangePass);

        //if(u.getGender()==1)
        Gender.setLayout(new GridLayout(1, 2));
        JLabel jLabelgendertitle = new JLabel("Giới tính:");
        jLabelgendertitle.setFont(new Font("a", Font.PLAIN, 24));

        JLabel jLabelgender = new JLabel();
        jLabelgender.setFont(new Font("a", Font.PLAIN, 24));

        if (u.getGender() == 0) {
            jLabelgender.setText("Nam");
        } else {
            jLabelgender.setText("Nữ");
        }

        Gender.add(jLabelgendertitle);
        Gender.add(jLabelgender);

        Email.setLayout(new GridLayout(1, 2));
        JLabel jLabelemailtitle = new JLabel("Email:");
        JLabel jLabelemail = new JLabel(u.getEmail());
        jLabelemailtitle.setFont(new Font("a", Font.PLAIN, 24));
        jLabelemail.setFont(new Font("a", Font.PLAIN, 24));

        Email.add(jLabelemailtitle);
        Email.add(jLabelemail);

        CreateTime.setLayout(new GridLayout(1, 2));
        JLabel jLabelCreatetimetitle = new JLabel("Thời gian lập:");
        JLabel jLabelcreatetime = new JLabel(u.getCreatedTime().toString());
        jLabelCreatetimetitle.setFont(new Font("a", Font.PLAIN, 24));
        jLabelcreatetime.setFont(new Font("a", Font.PLAIN, 24));

        CreateTime.add(jLabelCreatetimetitle);
        CreateTime.add(jLabelcreatetime);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Username = new javax.swing.JPanel();
        Password = new javax.swing.JPanel();
        buttonChangePass = new javax.swing.JButton();
        Gender = new javax.swing.JPanel();
        Email = new javax.swing.JPanel();
        CreateTime = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        back_gioithieu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(5, 1));

        javax.swing.GroupLayout UsernameLayout = new javax.swing.GroupLayout(Username);
        Username.setLayout(UsernameLayout);
        UsernameLayout.setHorizontalGroup(
            UsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2300, Short.MAX_VALUE)
        );
        UsernameLayout.setVerticalGroup(
            UsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 99, Short.MAX_VALUE)
        );

        jPanel1.add(Username);

        buttonChangePass.setText("Đổi mật khẩu");
        buttonChangePass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonChangePassMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PasswordLayout = new javax.swing.GroupLayout(Password);
        Password.setLayout(PasswordLayout);
        PasswordLayout.setHorizontalGroup(
            PasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PasswordLayout.createSequentialGroup()
                .addGap(369, 369, 369)
                .addComponent(buttonChangePass, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1832, Short.MAX_VALUE))
        );
        PasswordLayout.setVerticalGroup(
            PasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PasswordLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(buttonChangePass)
                .addContainerGap())
        );

        jPanel1.add(Password);

        javax.swing.GroupLayout GenderLayout = new javax.swing.GroupLayout(Gender);
        Gender.setLayout(GenderLayout);
        GenderLayout.setHorizontalGroup(
            GenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2300, Short.MAX_VALUE)
        );
        GenderLayout.setVerticalGroup(
            GenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 99, Short.MAX_VALUE)
        );

        jPanel1.add(Gender);

        javax.swing.GroupLayout EmailLayout = new javax.swing.GroupLayout(Email);
        Email.setLayout(EmailLayout);
        EmailLayout.setHorizontalGroup(
            EmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2300, Short.MAX_VALUE)
        );
        EmailLayout.setVerticalGroup(
            EmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 99, Short.MAX_VALUE)
        );

        jPanel1.add(Email);

        javax.swing.GroupLayout CreateTimeLayout = new javax.swing.GroupLayout(CreateTime);
        CreateTime.setLayout(CreateTimeLayout);
        CreateTimeLayout.setHorizontalGroup(
            CreateTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2300, Short.MAX_VALUE)
        );
        CreateTimeLayout.setVerticalGroup(
            CreateTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 99, Short.MAX_VALUE)
        );

        jPanel1.add(CreateTime);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        back_gioithieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_gioithieuMouseClicked(evt);
            }
        });
        jPanel2.add(back_gioithieu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_gioithieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_gioithieuMouseClicked
        Home lo = new Home();
        lo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back_gioithieuMouseClicked

    private void buttonChangePassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonChangePassMouseClicked
            DoiMatKhau doiMatKhau=new DoiMatKhau();
            doiMatKhau.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_buttonChangePassMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YourProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YourProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YourProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YourProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YourProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CreateTime;
    private javax.swing.JPanel Email;
    private javax.swing.JPanel Gender;
    private javax.swing.JPanel Password;
    private javax.swing.JPanel Username;
    private javax.swing.JLabel back_gioithieu;
    private javax.swing.JButton buttonChangePass;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
